apiVersion: v1
kind: ConfigMap
metadata:
  name: password-self-service
data:
  password-self-service.yaml: |
    server:
      # 运行模式(debug/release,正式版改为release)
      mode: debug
      # 程序监听端口
      addr: ":8080"
      # 限流配置, 最低纬度每秒一个请求，默认允许每秒一个请求
      rate-limit: 10
      # rsa公钥文件路径
      rsa-public-key: public.pem
      # rsa私钥文件路径
      rsa-private-key: private.pem
    
    redis:
      # 缓存数据库地址
      host: redis.database.svc.cluster.local
      # 缓存数据库端口
      port: 6379
      # 缓存数据库密码
      password: password
      # 缓存数据库编号
      db: 9
    
    ldap:
      # LDAP 服务器
      host: 127.0.0.1
      # LDAP 服务器端口
      port: 636
      # 是否开启TLS，AD域控支持修改密码时必须开启
      tls: true
      # LDAP 连接用户
      username: CN=devops,OU=ServiceAccount,OU=company,DC=kubeop,DC=local
      # LDAP 连接密码
      password: a123456
      # LDAP 搜索基础DN
      base: OU=company,DC=kubeop,DC=local
      # LDAP 过滤规则
      filter: (sAMAccountName=%s)
      # LDAP 搜索超时限制
      time-limit: 30
      # LDAP 搜索大小限制
      size-limit: 1000
    
    cron:
      # 定期检查密码是否过期, 7天内过期发送通知消息
      enabled: true
      schedule: "0 10 09 * * *"
    
    # 发送验证码和密码过期通知的通道
    channel:
      # 密码自助平台访问地址
      platform-url: https://aq.kubeop.com
      # 发送验证码通道
      verify-channel: mail
      # 发送密码过期通知通道
      expired-channel: mail
      # 邮箱通道配置，不使用可以不配置
      mail:
        # 邮箱 SMTP 服务器
        host: smtp.qiye.aliyun.com
        # 邮箱 SMTP 服务器端口
        port: 465
        # 是否开启TLS
        tls: true
        # 发件人邮箱地址
        user: xxx@kubeop.com
        # 发件人邮箱密码
        password: xxxxxx
        # 发件人来源
        from: 密码自助平台
      # 阿里云短信通道配置，不使用可以不配置
      aliyunsms:
        # 阿里云短信访问密钥
        access-key-id: xxxxxx
        # 阿里云短信访问密钥密钥
        access-key-secret: zzzzzz
        # 阿里云短信签名
        sign-name: 短信签名
        # 阿里云短信验证码模板
        template-code-verify: SMS_261400004
        # 阿里云短信密码过期通知模板
        template-code-expired: SMS_261400005
      # 腾讯云短信通道配置，不使用可以不配置
      tencentsms:
        # 腾讯云短信访问密钥
        access-key-id: xxxxxx
        # 腾讯云短信访问密钥密钥
        access-key-secret: zzzzzz
        # 腾讯云短信签名
        sign-name: 短信签名
        # 腾讯云短信区域, 仅支持ap-beijing、ap-guangzhou、ap-nanjing
        region: ap-beijing
        # 腾讯云短信应用ID
        app-id: 1234
        # 腾讯云短信验证码模板
        template-code-verify: SMS_261400004
        # 腾讯云短信密码过期通知模板
        template-code-expired: SMS_261400005
