// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/captcha/send": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Captcha"
                ],
                "summary": "获取验证码",
                "parameters": [
                    {
                        "description": "获取验证码",
                        "name": "sendCaptcha",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/captcha.sendCaptchaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.JsonRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.JsonRes"
                        }
                    }
                }
            }
        },
        "/captcha/verify": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Captcha"
                ],
                "summary": "校验验证码",
                "parameters": [
                    {
                        "description": "校验验证码",
                        "name": "VerifyCaptcha",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/captcha.verifyCaptchaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.JsonRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.JsonRes"
                        }
                    }
                }
            }
        },
        "/reset-password": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "重置密码",
                "parameters": [
                    {
                        "description": "重置密码",
                        "name": "ResetPassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/password.resetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.JsonRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.JsonRes"
                        }
                    }
                }
            }
        },
        "/unlock-account": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "解锁账户",
                "parameters": [
                    {
                        "description": "解锁账户",
                        "name": "UnlockAccount",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.unlockAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.JsonRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.JsonRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account.unlockAccountRequest": {
            "type": "object",
            "required": [
                "code",
                "username"
            ],
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2
                }
            }
        },
        "captcha.sendCaptchaRequest": {
            "type": "object",
            "required": [
                "category",
                "username"
            ],
            "properties": {
                "category": {
                    "description": "类别",
                    "type": "string",
                    "enum": [
                        "account",
                        "password"
                    ]
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "captcha.verifyCaptchaRequest": {
            "type": "object",
            "required": [
                "category",
                "code",
                "username"
            ],
            "properties": {
                "category": {
                    "description": "类别",
                    "type": "string",
                    "enum": [
                        "account",
                        "password"
                    ]
                },
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "password.resetPasswordRequest": {
            "type": "object",
            "required": [
                "code",
                "newPassword",
                "username"
            ],
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "newPassword": {
                    "description": "新密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2
                }
            }
        },
        "response.JsonRes": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码((0:成功, 1:失败, \u003e1:错误码))",
                    "type": "integer"
                },
                "data": {
                    "description": "返回数据(业务接口定义具体数据结构)"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger API",
	Description:      "AD密码自助平台",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
